version: '3.8'

services:
  worker:
    image: ${DOCKER_IMAGE_NAME}
    container_name: ops_worker
    env_file: ./.env
    working_dir: /opt/app
    volumes:
      - .:/opt/app
    depends_on:
      - db
    command:
      - /usr/bin/sleep
      - "99999"

  db:
    image: postgres:13
    container_name: ops_db
    environment:
      POSTGRES_DB: ops_db
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    volumes:
      - postgres_data:/var/lib/postgresql/data


  pgadmin:
    image: dpage/pgadmin4
    container_name: ops_pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5050:80" # localhost:5050
    depends_on:
      - db
    volumes:
      - pgadmin_data:/var/lib/pgadmin

volumes:
  postgres_data:
  pgadmin_data:

