version: '3.8'

services:
  worker:
    image: ${DOCKER_IMAGE_NAME}
    container_name: ops_worker
    env_file: ./.env
    working_dir: /opt/app
    volumes:
      - .:/opt/app
    depends_on:
      - db
    command:
      - /usr/bin/sleep
      - "99999"

  db:
    image: postgres:13
    container_name: ${DB_NAME}
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
     - "${DB_PORT_HOST}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: ops_pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PG_ADMIN_USER}
      PGADMIN_DEFAULT_PASSWORD: ${PG_ADMIN_PASSWORD}
    ports:
      - "5050:80" # localhost:5050
    depends_on:
      - db
    volumes:
      - pgadmin_data:/var/lib/pgadmin

volumes:
  postgres_data:
  pgadmin_data:

